### PR TITLE
Test codecov

### PR DESCRIPTION
**Pull request by Sean-Der**
#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by at-wat** [comment]
I'm not very sure why CODECOV_TOKEN is changed from secret to plain variable.

https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes says
> PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token)

**Comment by Sean-Der** [comment]
@at-wat I couldn’t get it to work, it would error that token wasn’t provided.

Do we need different jobs for PR and push to master maybe?

**Comment by at-wat** [comment]
@Sean-Der I confirmed that the upload just works without CODECOV_TOKEN secret for fork PR
https://github.com/pion/ci-sandbox/actions/runs/8609041154/job/23592380300
> ```
> info - 2024-04-09 01:42:58,540 -- The PR is happening in a forked repo. Using tokenless upload.
> info - 2024-04-09 01:43:02,194 -- Your upload is now processing. When finished, results will be available at: https://app.codecov.io/github/pion/ci-sandbox/commit/42d0041bd6509a619f233f68c5793404e01c9860
> info - 2024-04-09 01:43:02,374 -- Process Upload complete
> ```

**Comment by Sean-Der** [comment]
Thank you @at-wat ! Sorry I didn’t do this right, keep getting pulled away

**Pull request closed without merging**
